[project]
name = "vimmhash"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "requests>=2.34.2",
    "util @ git+https://github.com/mariomadproductions/py-util@e1caf6141d3b42c90118fd1ea04bd8594e219884",
]

[project.scripts]
vimmhash = "vimmhash:main"

[build-system]
requires = ["uv_build>=0.11.29,<0.12.0"]
build-backend = "uv_build"
